In [1]:
import numpy as np
print(np.__version__)

1.19.5


In [3]:
arr = np.arange(10) # start stop step values 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.full((3,3),True,dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.ones((3,3),dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,])

In [7]:
arr[arr%2 ==1]

array([1, 3, 5, 7, 9])

In [8]:
arr[arr%2==1] = -1


In [9]:
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
#a.setdiff()

In [11]:
## mathcing np.where()

In [12]:
# url = " "
# ds = np.genfromtxt(url, delimiter = ',' dtype = 'object')
#names = ('sepallength', 'sepalwidth','petallength','petalwidth', 'species') ## coloumn/attributes names  of data set

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/irsi.data'
ds = np.genfromtxt(url, delimiter = ',' dtype = 'object')